#=================================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================

name: Build_rockpi_4b

on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone source code
      env: 
        REPO_URL: https://github.com/radxa/rockchip-bsp.git
        REPO_BRANCH: master
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH rockchip-bsp
        cd rockchip-bsp
        git submodule init
        git submodule update
        
    - name: Build firmware
      env:
        ARCH: arm64
        RELEASE: buster
        TARGET: desktop
      working-directory: ./rockchip-bsp
      run: |
         ./build/mk-uboot.sh rockpi4b
         ./build/mk-kernel.sh rockpi4b
         cd rootfs
         sudo -E dpkg -i ubuntu-build-service/packages/*
         sudo -E apt-get install -f
         ./mk-base-debian.sh
         cd ..
         build/mk-image.sh -c rk3399 -t system -r rootfs/linaro-rootfs.img
         build/mk-image.sh -c rk3399 -b rockpi4 -t system -r rootfs/linaro-rootfs.img

    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: rockpi4b-debian
        path: rockchip-bsp/out
