name: Build_RockPi_4b

on: 
  release:
    types: [published]

  push:
    branches: 
      - master

  #schedule:
  #  - cron: 0 8 * * 5
  
  #watch:
  #  types: [started]

jobs:
  RockPi_4b:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@master
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y gcc-aarch64-linux-gnu device-tree-compiler libncurses5 libncurses5-dev build-essential libssl-dev mtools bc python dosfstools python-dbus python-debian python-yaml u-boot-tools python-support
        for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done
        sudo -E ln -sf /usr/include/asm-generic /usr/include/asm
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E swapoff -a
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/radxa/rockchip-bsp.git
        REPO_BRANCH: master
      run: |
        cd "/home/runner"
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH rockchip-bsp
        cd rockchip-bsp
        git submodule init
        git submodule update
    - name: Build firmware For uboot
      env:
        ARCH: arm64
        RELEASE: buster
        TARGET: desktop
      working-directory: /home/runner/rockchip-bsp
      run: |
         ./build/mk-uboot.sh rockpi4b
    - name: Build firmware  For kernel
      env:
        ARCH: arm64
        RELEASE: buster
        TARGET: desktop
      working-directory: /home/runner/rockchip-bsp
      run: |
         ./build/mk-kernel.sh rockpi4b
    - name: Build firmware  For rootfs
      env:
        ARCH: arm64
        RELEASE: buster
        TARGET: desktop
      working-directory: /home/runner/rockchip-bsp
      run: |
         cd rootfs
         sudo -E dpkg -i ubuntu-build-service/packages/*
         sudo -E apt-get install -f
         ./mk-base-debian.sh
    - name: Build firmware  For boot image
      env:
        ARCH: arm64
        RELEASE: buster
        TARGET: desktop
      working-directory: /home/runner/rockchip-bsp
      run: |
         ./build/mk-image.sh -c rk3399 -t system -r rootfs/linaro-rootfs.img
    - name: Build firmware  For system image
      env:
        ARCH: arm64
        RELEASE: buster
        TARGET: desktop
      working-directory: /home/runner/rockchip-bsp
      run: |
         ./build/mk-image.sh -c rk3399 -b rockpi4 -t system -r rootfs/linaro-rootfs.img
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: RockPi
        path: /home/runner/rockchip-bsp/out
